# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_install_hook_types: [pre-commit, pre-push, commit-msg]
default_stages: [pre-commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-merge-conflict
    - id: check-ast
    - id: trailing-whitespace
    - id: check-symlinks
    - id: name-tests-test
      args: [ --pytest-test-first ]
    - id: no-commit-to-branch
      args: [ -b , main ]
    - id: requirements-txt-fixer
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
    - id: pyupgrade
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.25.1
  hooks:
    - id: gitleaks
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.9
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    - id: mypy
      verbose: true
      args: [ --install-types, --non-interactive, --pretty, --disallow-untyped-defs, --strict-equality,  --warn-no-return, --ignore-missing-imports ]
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.6.3
  hooks:
    - id: commitizen
      stages: [commit-msg]
    - id: commitizen-branch
      stages: [pre-push]